export const  FETCH_REPO_ISSUES_REQUESTED = 
    'api/issueList/FETCH_REPO_ISSUES_REQUESTED';
export const  FETCH_REPO_ISSUES_SUCCESS = 
    'api/issueList/FETCH_REPO_ISSUES_SUCCESS';
export const  FETCH_REPO_ISSUES_FAILURE = 
    'api/issueList/FETCH_REPO_ISSUES_FAILURE';
export const UPDATE_SEARCH_TEXT =
    'api/issueList/UPDATE_SEARCH_TEXT';
export  const GET_COMMENTS_FOR_ISSUE_REQUESTED = 
    'api/issueList/GET_COMMENTS_FOR_ISSUE_REQUESTED';
export  const GET_COMMENTS_FOR_ISSUE_SUCCESS = 
    'api/issueList/GET_COMMENTS_FOR_ISSUE_SUCCESS';
export  const GET_COMMENTS_FOR_ISSUE_ERRORED = 
    'api/issueList/GET_COMMENTS_FOR_ISSUE_ERRORED';
export const  FETCH_SINGLE_ISSUE_REQUESTED = 
    'api/issueList/FETCH_SINGLE_ISSUE_REQUESTED';
export const  FETCH_SINGLE_ISSUE_SUCCESS = 
    'api/issueList/FETCH_SINGLE_ISSUE_SUCCESS';
export const  FETCH_SINGLE_ISSUE_FAILURE = 
    'api/issueList/FETCH_SINGLE_ISSUE_FAILURE';